<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="15">
<syndb class_id="0" tracking_level="0" version="0">
	<userIPLatency>-1</userIPLatency>
	<userIPName></userIPName>
	<cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
		<name>bitwise_and</name>
		<ret_bitwidth>0</ret_bitwidth>
		<ports class_id="2" tracking_level="0" version="0">
			<count>3</count>
			<item_version>0</item_version>
			<item class_id="3" tracking_level="1" version="0" object_id="_1">
				<Value class_id="4" tracking_level="0" version="0">
					<Obj class_id="5" tracking_level="0" version="0">
						<type>1</type>
						<id>1</id>
						<name>p_src1_data_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo class_id="6" tracking_level="0" version="0">
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>_src1.data.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs class_id="7" tracking_level="0" version="0">
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_2">
				<Value>
					<Obj>
						<type>1</type>
						<id>2</id>
						<name>p_src2_data_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>_src2.data.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<direction>0</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
			<item class_id_reference="3" object_id="_3">
				<Value>
					<Obj>
						<type>1</type>
						<id>3</id>
						<name>p_dst_data_V</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>_dst.data.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<direction>1</direction>
				<if_type>3</if_type>
				<array_size>0</array_size>
				<bit_vecs>
					<count>0</count>
					<item_version>0</item_version>
				</bit_vecs>
			</item>
		</ports>
		<nodes class_id="8" tracking_level="0" version="0">
			<count>18</count>
			<item_version>0</item_version>
			<item class_id="9" tracking_level="1" version="0" object_id="_4">
				<Value>
					<Obj>
						<type>0</type>
						<id>7</id>
						<name>_ln295</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>295</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item class_id="10" tracking_level="0" version="0">
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second class_id="11" tracking_level="0" version="0">
									<count>2</count>
									<item_version>0</item_version>
									<item class_id="12" tracking_level="0" version="0">
										<first class_id="13" tracking_level="0" version="0">
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>295</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>41</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.76</m_delay>
				<m_topoIndex>1</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_5">
				<Value>
					<Obj>
						<type>0</type>
						<id>9</id>
						<name>t_V_12</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName>i.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>43</item>
					<item>44</item>
					<item>45</item>
					<item>46</item>
				</oprand_edges>
				<opcode>phi</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>2</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_6">
				<Value>
					<Obj>
						<type>0</type>
						<id>10</id>
						<name>icmp_ln887</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>295</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>295</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>47</item>
					<item>49</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.55</m_delay>
				<m_topoIndex>3</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_7">
				<Value>
					<Obj>
						<type>0</type>
						<id>11</id>
						<name>i_V</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>295</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>295</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>i.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>50</item>
					<item>52</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.91</m_delay>
				<m_topoIndex>4</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_8">
				<Value>
					<Obj>
						<type>0</type>
						<id>12</id>
						<name>_ln295</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>295</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>295</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>53</item>
					<item>54</item>
					<item>55</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>5</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_9">
				<Value>
					<Obj>
						<type>0</type>
						<id>17</id>
						<name>_ln301</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>301</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>301</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>56</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.76</m_delay>
				<m_topoIndex>6</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_10">
				<Value>
					<Obj>
						<type>0</type>
						<id>19</id>
						<name>t_V</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>301</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>301</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<oprand_edges>
					<count>4</count>
					<item_version>0</item_version>
					<item>58</item>
					<item>59</item>
					<item>60</item>
					<item>61</item>
				</oprand_edges>
				<opcode>phi</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>8</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_11">
				<Value>
					<Obj>
						<type>0</type>
						<id>20</id>
						<name>icmp_ln301</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>301</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>301</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>1</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>62</item>
					<item>64</item>
				</oprand_edges>
				<opcode>icmp</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.66</m_delay>
				<m_topoIndex>9</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_12">
				<Value>
					<Obj>
						<type>0</type>
						<id>21</id>
						<name>add_ln887</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>301</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>301</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>65</item>
					<item>67</item>
				</oprand_edges>
				<opcode>add</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>1.82</m_delay>
				<m_topoIndex>10</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_13">
				<Value>
					<Obj>
						<type>0</type>
						<id>22</id>
						<name>_ln301</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>301</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>301</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>68</item>
					<item>69</item>
					<item>70</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>11</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_14">
				<Value>
					<Obj>
						<type>0</type>
						<id>28</id>
						<name>p_src1_data_V_read</name>
						<fileName>D:/Xilinx/xfopencv-master/include\common/xf_structs.h</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>622</lineNumber>
						<contextFuncName>read</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\common/xf_structs.h</first>
											<second>read</second>
										</first>
										<second>622</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>306</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>2</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>72</item>
					<item>73</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>3.63</m_delay>
				<m_topoIndex>12</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_15">
				<Value>
					<Obj>
						<type>0</type>
						<id>29</id>
						<name>val_src1_V</name>
						<fileName>D:/Xilinx/xfopencv-master/include\common/xf_structs.h</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>622</lineNumber>
						<contextFuncName>read</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\common/xf_structs.h</first>
											<second>read</second>
										</first>
										<second>622</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>306</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>val_src1.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>74</item>
				</oprand_edges>
				<opcode>sext</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>13</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_16">
				<Value>
					<Obj>
						<type>0</type>
						<id>30</id>
						<name>val_src2_V</name>
						<fileName>D:/Xilinx/xfopencv-master/include\common/xf_structs.h</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>622</lineNumber>
						<contextFuncName>read</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\common/xf_structs.h</first>
											<second>read</second>
										</first>
										<second>622</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>307</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>val_src2.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>76</item>
					<item>77</item>
				</oprand_edges>
				<opcode>read</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>3.63</m_delay>
				<m_topoIndex>14</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_17">
				<Value>
					<Obj>
						<type>0</type>
						<id>31</id>
						<name>and_ln1355</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>316</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>316</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName>op2.V</originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<oprand_edges>
					<count>2</count>
					<item_version>0</item_version>
					<item>78</item>
					<item>79</item>
				</oprand_edges>
				<opcode>and</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.99</m_delay>
				<m_topoIndex>15</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_18">
				<Value>
					<Obj>
						<type>0</type>
						<id>32</id>
						<name>p_dst_data_V_write_ln651</name>
						<fileName>D:/Xilinx/xfopencv-master/include\common/xf_structs.h</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>651</lineNumber>
						<contextFuncName>write</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>3</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\common/xf_structs.h</first>
											<second>write</second>
										</first>
										<second>651</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>319</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>3</count>
					<item_version>0</item_version>
					<item>81</item>
					<item>82</item>
					<item>83</item>
				</oprand_edges>
				<opcode>write</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>3.63</m_delay>
				<m_topoIndex>16</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_19">
				<Value>
					<Obj>
						<type>0</type>
						<id>34</id>
						<name>_ln301</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>301</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>301</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>84</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>17</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_20">
				<Value>
					<Obj>
						<type>0</type>
						<id>37</id>
						<name>_ln295</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>295</lineNumber>
						<contextFuncName>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>2</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>589</second>
									</item>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>xFBitwiseANDKernel&amp;lt;0, 180, 320, 1, 0, 1, 1, 1, 320&amp;gt;</second>
										</first>
										<second>295</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>1</count>
					<item_version>0</item_version>
					<item>85</item>
				</oprand_edges>
				<opcode>br</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>18</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
			<item class_id_reference="9" object_id="_21">
				<Value>
					<Obj>
						<type>0</type>
						<id>39</id>
						<name>_ln591</name>
						<fileName>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</fileName>
						<fileDirectory>D:\GitHub\Weed_Detection\WD_HLS</fileDirectory>
						<lineNumber>591</lineNumber>
						<contextFuncName>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</contextFuncName>
						<inlineStackInfo>
							<count>1</count>
							<item_version>0</item_version>
							<item>
								<first>D:\GitHub\Weed_Detection\WD_HLS</first>
								<second>
									<count>1</count>
									<item_version>0</item_version>
									<item>
										<first>
											<first>D:/Xilinx/xfopencv-master/include\core/xf_arithm.hpp</first>
											<second>bitwise_and&amp;lt;0, 180, 320, 1&amp;gt;</second>
										</first>
										<second>591</second>
									</item>
								</second>
							</item>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>0</bitwidth>
				</Value>
				<oprand_edges>
					<count>0</count>
					<item_version>0</item_version>
				</oprand_edges>
				<opcode>ret</opcode>
				<m_Display>0</m_Display>
				<m_isOnCriticalPath>0</m_isOnCriticalPath>
				<m_isLCDNode>0</m_isLCDNode>
				<m_isStartOfPath>0</m_isStartOfPath>
				<m_delay>0.00</m_delay>
				<m_topoIndex>7</m_topoIndex>
				<m_clusterGroupNumber>-1</m_clusterGroupNumber>
			</item>
		</nodes>
		<consts class_id="15" tracking_level="0" version="0">
			<count>6</count>
			<item_version>0</item_version>
			<item class_id="16" tracking_level="1" version="0" object_id="_22">
				<Value>
					<Obj>
						<type>2</type>
						<id>42</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_23">
				<Value>
					<Obj>
						<type>2</type>
						<id>48</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>180</content>
			</item>
			<item class_id_reference="16" object_id="_24">
				<Value>
					<Obj>
						<type>2</type>
						<id>51</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>8</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
			<item class_id_reference="16" object_id="_25">
				<Value>
					<Obj>
						<type>2</type>
						<id>57</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>0</content>
			</item>
			<item class_id_reference="16" object_id="_26">
				<Value>
					<Obj>
						<type>2</type>
						<id>63</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>320</content>
			</item>
			<item class_id_reference="16" object_id="_27">
				<Value>
					<Obj>
						<type>2</type>
						<id>66</id>
						<name>empty</name>
						<fileName></fileName>
						<fileDirectory></fileDirectory>
						<lineNumber>0</lineNumber>
						<contextFuncName></contextFuncName>
						<inlineStackInfo>
							<count>0</count>
							<item_version>0</item_version>
						</inlineStackInfo>
						<originalName></originalName>
						<rtlName></rtlName>
						<coreName></coreName>
					</Obj>
					<bitwidth>9</bitwidth>
				</Value>
				<const_type>0</const_type>
				<content>1</content>
			</item>
		</consts>
		<blocks class_id="17" tracking_level="0" version="0">
			<count>7</count>
			<item_version>0</item_version>
			<item class_id="18" tracking_level="1" version="0" object_id="_28">
				<Obj>
					<type>3</type>
					<id>8</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>7</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_29">
				<Obj>
					<type>3</type>
					<id>13</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>9</item>
					<item>10</item>
					<item>11</item>
					<item>12</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_30">
				<Obj>
					<type>3</type>
					<id>18</id>
					<name>rowLoop_begin</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>17</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_31">
				<Obj>
					<type>3</type>
					<id>23</id>
					<name></name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>4</count>
					<item_version>0</item_version>
					<item>19</item>
					<item>20</item>
					<item>21</item>
					<item>22</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_32">
				<Obj>
					<type>3</type>
					<id>35</id>
					<name>colLoop</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>6</count>
					<item_version>0</item_version>
					<item>28</item>
					<item>29</item>
					<item>30</item>
					<item>31</item>
					<item>32</item>
					<item>34</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_33">
				<Obj>
					<type>3</type>
					<id>38</id>
					<name>rowLoop_end</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>37</item>
				</node_objs>
			</item>
			<item class_id_reference="18" object_id="_34">
				<Obj>
					<type>3</type>
					<id>40</id>
					<name>xFBitwiseANDKernel&lt;0, 180, 320, 1, 0, 1, 1, 1, 320&gt;.exit</name>
					<fileName></fileName>
					<fileDirectory></fileDirectory>
					<lineNumber>0</lineNumber>
					<contextFuncName></contextFuncName>
					<inlineStackInfo>
						<count>0</count>
						<item_version>0</item_version>
					</inlineStackInfo>
					<originalName></originalName>
					<rtlName></rtlName>
					<coreName></coreName>
				</Obj>
				<node_objs>
					<count>1</count>
					<item_version>0</item_version>
					<item>39</item>
				</node_objs>
			</item>
		</blocks>
		<edges class_id="19" tracking_level="0" version="0">
			<count>41</count>
			<item_version>0</item_version>
			<item class_id="20" tracking_level="1" version="0" object_id="_35">
				<id>41</id>
				<edge_type>2</edge_type>
				<source_obj>13</source_obj>
				<sink_obj>7</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_36">
				<id>43</id>
				<edge_type>1</edge_type>
				<source_obj>42</source_obj>
				<sink_obj>9</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_37">
				<id>44</id>
				<edge_type>2</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>9</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_38">
				<id>45</id>
				<edge_type>1</edge_type>
				<source_obj>11</source_obj>
				<sink_obj>9</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_39">
				<id>46</id>
				<edge_type>2</edge_type>
				<source_obj>38</source_obj>
				<sink_obj>9</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_40">
				<id>47</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>10</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_41">
				<id>49</id>
				<edge_type>1</edge_type>
				<source_obj>48</source_obj>
				<sink_obj>10</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_42">
				<id>50</id>
				<edge_type>1</edge_type>
				<source_obj>9</source_obj>
				<sink_obj>11</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_43">
				<id>52</id>
				<edge_type>1</edge_type>
				<source_obj>51</source_obj>
				<sink_obj>11</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_44">
				<id>53</id>
				<edge_type>1</edge_type>
				<source_obj>10</source_obj>
				<sink_obj>12</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_45">
				<id>54</id>
				<edge_type>2</edge_type>
				<source_obj>40</source_obj>
				<sink_obj>12</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_46">
				<id>55</id>
				<edge_type>2</edge_type>
				<source_obj>18</source_obj>
				<sink_obj>12</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_47">
				<id>56</id>
				<edge_type>2</edge_type>
				<source_obj>23</source_obj>
				<sink_obj>17</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_48">
				<id>58</id>
				<edge_type>1</edge_type>
				<source_obj>57</source_obj>
				<sink_obj>19</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_49">
				<id>59</id>
				<edge_type>2</edge_type>
				<source_obj>18</source_obj>
				<sink_obj>19</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_50">
				<id>60</id>
				<edge_type>1</edge_type>
				<source_obj>21</source_obj>
				<sink_obj>19</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_51">
				<id>61</id>
				<edge_type>2</edge_type>
				<source_obj>35</source_obj>
				<sink_obj>19</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_52">
				<id>62</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>20</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_53">
				<id>64</id>
				<edge_type>1</edge_type>
				<source_obj>63</source_obj>
				<sink_obj>20</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_54">
				<id>65</id>
				<edge_type>1</edge_type>
				<source_obj>19</source_obj>
				<sink_obj>21</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_55">
				<id>67</id>
				<edge_type>1</edge_type>
				<source_obj>66</source_obj>
				<sink_obj>21</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_56">
				<id>68</id>
				<edge_type>1</edge_type>
				<source_obj>20</source_obj>
				<sink_obj>22</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_57">
				<id>69</id>
				<edge_type>2</edge_type>
				<source_obj>35</source_obj>
				<sink_obj>22</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_58">
				<id>70</id>
				<edge_type>2</edge_type>
				<source_obj>38</source_obj>
				<sink_obj>22</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_59">
				<id>73</id>
				<edge_type>1</edge_type>
				<source_obj>1</source_obj>
				<sink_obj>28</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_60">
				<id>74</id>
				<edge_type>1</edge_type>
				<source_obj>28</source_obj>
				<sink_obj>29</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_61">
				<id>77</id>
				<edge_type>1</edge_type>
				<source_obj>2</source_obj>
				<sink_obj>30</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_62">
				<id>78</id>
				<edge_type>1</edge_type>
				<source_obj>30</source_obj>
				<sink_obj>31</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_63">
				<id>79</id>
				<edge_type>1</edge_type>
				<source_obj>29</source_obj>
				<sink_obj>31</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_64">
				<id>82</id>
				<edge_type>1</edge_type>
				<source_obj>3</source_obj>
				<sink_obj>32</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_65">
				<id>83</id>
				<edge_type>1</edge_type>
				<source_obj>31</source_obj>
				<sink_obj>32</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_66">
				<id>84</id>
				<edge_type>2</edge_type>
				<source_obj>23</source_obj>
				<sink_obj>34</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_67">
				<id>85</id>
				<edge_type>2</edge_type>
				<source_obj>13</source_obj>
				<sink_obj>37</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_68">
				<id>188</id>
				<edge_type>2</edge_type>
				<source_obj>8</source_obj>
				<sink_obj>13</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_69">
				<id>189</id>
				<edge_type>2</edge_type>
				<source_obj>13</source_obj>
				<sink_obj>18</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_70">
				<id>190</id>
				<edge_type>2</edge_type>
				<source_obj>13</source_obj>
				<sink_obj>40</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_71">
				<id>191</id>
				<edge_type>2</edge_type>
				<source_obj>18</source_obj>
				<sink_obj>23</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_72">
				<id>192</id>
				<edge_type>2</edge_type>
				<source_obj>23</source_obj>
				<sink_obj>38</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_73">
				<id>193</id>
				<edge_type>2</edge_type>
				<source_obj>23</source_obj>
				<sink_obj>35</sink_obj>
				<is_back_edge>0</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_74">
				<id>194</id>
				<edge_type>2</edge_type>
				<source_obj>35</source_obj>
				<sink_obj>23</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
			<item class_id_reference="20" object_id="_75">
				<id>195</id>
				<edge_type>2</edge_type>
				<source_obj>38</source_obj>
				<sink_obj>13</sink_obj>
				<is_back_edge>1</is_back_edge>
			</item>
		</edges>
	</cdfg>
	<cdfg_regions class_id="21" tracking_level="0" version="0">
		<count>7</count>
		<item_version>0</item_version>
		<item class_id="22" tracking_level="1" version="0" object_id="_76">
			<mId>1</mId>
			<mTag>bitwise_and</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>3</count>
				<item_version>0</item_version>
				<item>2</item>
				<item>3</item>
				<item>7</item>
			</sub_regions>
			<basic_blocks>
				<count>0</count>
				<item_version>0</item_version>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>58141</mMinLatency>
			<mMaxLatency>58141</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_77">
			<mId>2</mId>
			<mTag>Entry</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>8</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_78">
			<mId>3</mId>
			<mTag>rowLoop</mTag>
			<mType>1</mType>
			<sub_regions>
				<count>3</count>
				<item_version>0</item_version>
				<item>4</item>
				<item>5</item>
				<item>6</item>
			</sub_regions>
			<basic_blocks>
				<count>0</count>
				<item_version>0</item_version>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>180</mMinTripCount>
			<mMaxTripCount>180</mMaxTripCount>
			<mMinLatency>58140</mMinLatency>
			<mMaxLatency>58140</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_79">
			<mId>4</mId>
			<mTag>Region 1</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>13</item>
				<item>18</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_80">
			<mId>5</mId>
			<mTag>colLoop</mTag>
			<mType>1</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>23</item>
				<item>35</item>
			</basic_blocks>
			<mII>1</mII>
			<mDepth>2</mDepth>
			<mMinTripCount>320</mMinTripCount>
			<mMaxTripCount>320</mMaxTripCount>
			<mMinLatency>320</mMinLatency>
			<mMaxLatency>320</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_81">
			<mId>6</mId>
			<mTag>Region 2</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>38</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
		<item class_id_reference="22" object_id="_82">
			<mId>7</mId>
			<mTag>Return</mTag>
			<mType>0</mType>
			<sub_regions>
				<count>0</count>
				<item_version>0</item_version>
			</sub_regions>
			<basic_blocks>
				<count>1</count>
				<item_version>0</item_version>
				<item>40</item>
			</basic_blocks>
			<mII>-1</mII>
			<mDepth>-1</mDepth>
			<mMinTripCount>-1</mMinTripCount>
			<mMaxTripCount>-1</mMaxTripCount>
			<mMinLatency>0</mMinLatency>
			<mMaxLatency>0</mMaxLatency>
			<mIsDfPipe>0</mIsDfPipe>
			<mDfPipe class_id="-1"></mDfPipe>
		</item>
	</cdfg_regions>
	<fsm class_id="-1"></fsm>
	<res class_id="-1"></res>
	<node_label_latency class_id="26" tracking_level="0" version="0">
		<count>18</count>
		<item_version>0</item_version>
		<item class_id="27" tracking_level="0" version="0">
			<first>7</first>
			<second class_id="28" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>9</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>10</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>11</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>12</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>17</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>19</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>20</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>21</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>22</first>
			<second>
				<first>2</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>28</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>29</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>30</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>31</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>32</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>34</first>
			<second>
				<first>3</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>37</first>
			<second>
				<first>4</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>39</first>
			<second>
				<first>1</first>
				<second>0</second>
			</second>
		</item>
	</node_label_latency>
	<bblk_ent_exit class_id="29" tracking_level="0" version="0">
		<count>7</count>
		<item_version>0</item_version>
		<item class_id="30" tracking_level="0" version="0">
			<first>8</first>
			<second class_id="31" tracking_level="0" version="0">
				<first>0</first>
				<second>0</second>
			</second>
		</item>
		<item>
			<first>13</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>18</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
		<item>
			<first>23</first>
			<second>
				<first>2</first>
				<second>2</second>
			</second>
		</item>
		<item>
			<first>35</first>
			<second>
				<first>3</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>38</first>
			<second>
				<first>3</first>
				<second>3</second>
			</second>
		</item>
		<item>
			<first>40</first>
			<second>
				<first>1</first>
				<second>1</second>
			</second>
		</item>
	</bblk_ent_exit>
	<regions class_id="32" tracking_level="0" version="0">
		<count>1</count>
		<item_version>0</item_version>
		<item class_id="33" tracking_level="1" version="0" object_id="_83">
			<region_name>colLoop</region_name>
			<basic_blocks>
				<count>2</count>
				<item_version>0</item_version>
				<item>23</item>
				<item>35</item>
			</basic_blocks>
			<nodes>
				<count>0</count>
				<item_version>0</item_version>
			</nodes>
			<anchor_node>-1</anchor_node>
			<region_type>8</region_type>
			<interval>1</interval>
			<pipe_depth>2</pipe_depth>
		</item>
	</regions>
	<dp_fu_nodes class_id="34" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes>
	<dp_fu_nodes_expression class_id="35" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_expression>
	<dp_fu_nodes_module>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_module>
	<dp_fu_nodes_io>
		<count>0</count>
		<item_version>0</item_version>
	</dp_fu_nodes_io>
	<return_ports>
		<count>0</count>
		<item_version>0</item_version>
	</return_ports>
	<dp_mem_port_nodes class_id="36" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_mem_port_nodes>
	<dp_reg_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_nodes>
	<dp_regname_nodes>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_nodes>
	<dp_reg_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_reg_phi>
	<dp_regname_phi>
		<count>0</count>
		<item_version>0</item_version>
	</dp_regname_phi>
	<dp_port_io_nodes class_id="37" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</dp_port_io_nodes>
	<port2core class_id="38" tracking_level="0" version="0">
		<count>0</count>
		<item_version>0</item_version>
	</port2core>
	<node2core>
		<count>0</count>
		<item_version>0</item_version>
	</node2core>
</syndb>
</boost_serialization>

