############################################################
## This file is generated automatically by Vivado HLS.
## Please DO NOT edit it.
## Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
############################################################
set_directive_pipeline "get_histogram/get_histogram_label0"
set_directive_pipeline "get_line_bases/get_line_bases_label1"
set_directive_pipeline "extract_micro_roi/extract_micro_roi_label2"
set_directive_pipeline "get_centroid_in_micro_roi/get_centroid_in_micro_roi_label3"
set_directive_unroll -factor 1 "get_exg_image/get_exg_image_label2"
set_directive_pipeline "get_12th_segment/get_12th_segment_label4"
set_directive_pipeline "sectors_weed_classification/sectors_weed_classification_label5"
set_directive_pipeline "sectors_weed_classification/sectors_weed_classification_label6"
set_directive_pipeline "get_last_centroids/get_last_centroids_label8"
set_directive_pipeline "get_vegetation_in_line/get_vegetation_in_line_label9"
set_directive_pipeline "initialize_limits/initialize_limits_label11"
set_directive_pipeline "hough_lines_filter/hough_lines_filter_label12"
set_directive_pipeline "extract_first_part_centroids/extract_first_part_centroids_label13"
set_directive_pipeline "extract_second_part_centroids/extract_second_part_centroids_label14"
set_directive_pipeline "get_final_lines/get_final_lines_label15"
set_directive_pipeline "get_weed_mask/get_weed_mask_label16"
set_directive_pipeline "independent_coef_correction/independent_coef_correction_label17"
set_directive_pipeline "weed_detection/weed_detection_label0"
set_directive_pipeline "get_exg_image/get_exg_image_label1"
set_directive_unroll -factor 1 "get_exg_image/get_exg_image_label1"
set_directive_unroll -factor 10 "extract_micro_roi/extract_micro_roi_label0"
set_directive_pipeline "is_crop_or_furrow/is_crop_or_furrow_label1"
set_directive_pipeline "is_crop_or_furrow/is_crop_or_furrow_label2"
set_directive_interface -mode ap_ctrl_none "ip_accel_app"
set_directive_pipeline "get_total_vegetation/get_total_vegetation_label0"
set_directive_pipeline "get_total_vegetation/get_total_vegetation_label1"
set_directive_pipeline "sectors_weed_classification/sectors_weed_classification_label16"
set_directive_pipeline "sectors_weed_classification/sectors_weed_classification_label1"
set_directive_pipeline "get_12th_segment/get_12th_segment_label2"
set_directive_pipeline "get_histogram/get_histogram_label3"
set_directive_pipeline "get_line_bases/get_line_bases_label4"
set_directive_pipeline "get_line_bases/get_line_bases_label0"
set_directive_pipeline "get_last_centroids/get_last_centroids_label9"
set_directive_pipeline "get_lines_lsl/get_lines_lsl_label0"
set_directive_pipeline "least_squares_line/least_squares_line_label10"
set_directive_pipeline "convert_fp_to_8b/convert_fp_to_8b_label1"
