// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _get_vegetation_image_4_HH_
#define _get_vegetation_image_4_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "get_vegetation_image_113.h"
#include "duplicateMat635769.h"
#include "duplicateMat.h"
#include "extract_channels.h"
#include "get_max_from_channel.h"
#include "get_vegetation_image.h"
#include "get_exg_image.h"
#include "get_vegetation_image_3.h"
#include "get_vegetation_image_2.h"
#include "convert_fp_to_8b770.h"
#include "fifo_w9_d2_A.h"
#include "fifo_w10_d2_A_x0.h"
#include "fifo_w24_d1_A.h"
#include "fifo_w8_d1_A.h"
#include "fifo_w32_d2_A_x.h"
#include "fifo_w32_d1_A.h"
#include "fifo_w28_d3_A.h"
#include "fifo_w29_d2_A.h"
#include "fifo_w24_d2_A_x1.h"
#include "fifo_w28_d2_A.h"
#include "start_for_duplicasc4.h"
#include "start_for_extracttde.h"

namespace ap_rtl {

struct get_vegetation_image_4 : public sc_module {
    // Port declarations 19
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<10> > img_in_cols_dout;
    sc_in< sc_logic > img_in_cols_empty_n;
    sc_out< sc_logic > img_in_cols_read;
    sc_in< sc_lv<24> > img_in_data_V_dout;
    sc_in< sc_logic > img_in_data_V_empty_n;
    sc_out< sc_logic > img_in_data_V_read;
    sc_out< sc_lv<8> > img_out_data_V_din;
    sc_in< sc_logic > img_out_data_V_full_n;
    sc_out< sc_logic > img_out_data_V_write;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_in< sc_logic > ap_continue;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_logic > ap_var_for_const2;
    sc_signal< sc_lv<8> > ap_var_for_const1;


    // Module declarations
    get_vegetation_image_4(sc_module_name name);
    SC_HAS_PROCESS(get_vegetation_image_4);

    ~get_vegetation_image_4();

    sc_trace_file* mVcdFile;

    get_vegetation_image_113* get_vegetation_image_113_U0;
    duplicateMat635769* duplicateMat635769_U0;
    duplicateMat* duplicateMat_U0;
    extract_channels* extract_channels_U0;
    get_max_from_channel* get_max_from_channel_U0;
    get_vegetation_image* get_vegetation_image_U0;
    get_exg_image* get_exg_image_U0;
    get_vegetation_image_3* get_vegetation_image_3_U0;
    get_vegetation_image_2* get_vegetation_image_2_U0;
    convert_fp_to_8b770* convert_fp_to_8b770_U0;
    fifo_w9_d2_A* img_in_0_rows_channe_U;
    fifo_w10_d2_A_x0* img_in_0_cols_channe_U;
    fifo_w10_d2_A_x0* img_in_cols_c_i_U;
    fifo_w24_d1_A* img_in_0_data_V_U;
    fifo_w24_d1_A* img_in_1_data_V_U;
    fifo_w24_d1_A* img_in_2_data_V_U;
    fifo_w24_d1_A* img_in_3_data_V_U;
    fifo_w8_d1_A* r_channel_data_V_U;
    fifo_w8_d1_A* g_channel_data_V_U;
    fifo_w8_d1_A* b_channel_data_V_U;
    fifo_w32_d2_A_x* max_r_c_i_U;
    fifo_w32_d2_A_x* max_g_c_i_U;
    fifo_w32_d2_A_x* max_b_c_i_U;
    fifo_w32_d2_A_x* max_r_c14_i_U;
    fifo_w32_d2_A_x* max_g_c15_i_U;
    fifo_w32_d2_A_x* max_b_c16_i_U;
    fifo_w32_d1_A* veg_temp_data_V_U;
    fifo_w28_d3_A* min_value_V_c_i_U;
    fifo_w29_d2_A* max_value_V_c_i_U;
    fifo_w24_d2_A_x1* extLd_cast_loc_chann_U;
    fifo_w28_d2_A* min_value_V_c17_i_U;
    fifo_w24_d2_A_x1* sub_ln703_cast_loc_c_U;
    start_for_duplicasc4* start_for_duplicasc4_U;
    start_for_extracttde* start_for_extracttde_U;
    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > get_vegetation_image_113_U0_ap_start;
    sc_signal< sc_logic > get_vegetation_image_113_U0_ap_done;
    sc_signal< sc_logic > get_vegetation_image_113_U0_ap_continue;
    sc_signal< sc_logic > get_vegetation_image_113_U0_ap_idle;
    sc_signal< sc_logic > get_vegetation_image_113_U0_ap_ready;
    sc_signal< sc_lv<9> > get_vegetation_image_113_U0_img_in_0_rows0;
    sc_signal< sc_logic > get_vegetation_image_113_U0_img_in_0_rows0_ap_vld;
    sc_signal< sc_lv<10> > get_vegetation_image_113_U0_img_in_0_cols0;
    sc_signal< sc_logic > get_vegetation_image_113_U0_img_in_0_cols0_ap_vld;
    sc_signal< sc_logic > get_vegetation_image_113_U0_img_in_cols_read;
    sc_signal< sc_lv<10> > get_vegetation_image_113_U0_img_in_cols_out_din;
    sc_signal< sc_logic > get_vegetation_image_113_U0_img_in_cols_out_write;
    sc_signal< sc_logic > ap_channel_done_img_in_0_cols_channe;
    sc_signal< sc_logic > img_in_0_cols_channe_full_n;
    sc_signal< sc_logic > ap_sync_reg_channel_write_img_in_0_cols_channe;
    sc_signal< sc_logic > ap_sync_channel_write_img_in_0_cols_channe;
    sc_signal< sc_logic > ap_channel_done_img_in_0_rows_channe;
    sc_signal< sc_logic > img_in_0_rows_channe_full_n;
    sc_signal< sc_logic > ap_sync_reg_channel_write_img_in_0_rows_channe;
    sc_signal< sc_logic > ap_sync_channel_write_img_in_0_rows_channe;
    sc_signal< sc_logic > duplicateMat635769_U0_ap_start;
    sc_signal< sc_logic > duplicateMat635769_U0_start_full_n;
    sc_signal< sc_logic > duplicateMat635769_U0_start_out;
    sc_signal< sc_logic > duplicateMat635769_U0_start_write;
    sc_signal< sc_logic > duplicateMat635769_U0_p_src_cols_read;
    sc_signal< sc_logic > duplicateMat635769_U0_p_src_data_V_read;
    sc_signal< sc_lv<24> > duplicateMat635769_U0_p_dst1_data_V_din;
    sc_signal< sc_logic > duplicateMat635769_U0_p_dst1_data_V_write;
    sc_signal< sc_lv<24> > duplicateMat635769_U0_p_dst2_data_V_din;
    sc_signal< sc_logic > duplicateMat635769_U0_p_dst2_data_V_write;
    sc_signal< sc_logic > duplicateMat635769_U0_ap_done;
    sc_signal< sc_logic > duplicateMat635769_U0_ap_ready;
    sc_signal< sc_logic > duplicateMat635769_U0_ap_idle;
    sc_signal< sc_logic > duplicateMat635769_U0_ap_continue;
    sc_signal< sc_logic > duplicateMat_U0_p_src_data_V_read;
    sc_signal< sc_lv<24> > duplicateMat_U0_p_dst1_data_V_din;
    sc_signal< sc_logic > duplicateMat_U0_p_dst1_data_V_write;
    sc_signal< sc_lv<24> > duplicateMat_U0_p_dst2_data_V_din;
    sc_signal< sc_logic > duplicateMat_U0_p_dst2_data_V_write;
    sc_signal< sc_logic > duplicateMat_U0_ap_start;
    sc_signal< sc_logic > duplicateMat_U0_ap_done;
    sc_signal< sc_logic > duplicateMat_U0_ap_ready;
    sc_signal< sc_logic > duplicateMat_U0_ap_idle;
    sc_signal< sc_logic > duplicateMat_U0_ap_continue;
    sc_signal< sc_logic > extract_channels_U0_img_in_0_data_V_read;
    sc_signal< sc_logic > extract_channels_U0_img_in_1_data_V_read;
    sc_signal< sc_logic > extract_channels_U0_img_in_2_data_V_read;
    sc_signal< sc_lv<8> > extract_channels_U0_r_channel_data_V_din;
    sc_signal< sc_logic > extract_channels_U0_r_channel_data_V_write;
    sc_signal< sc_lv<8> > extract_channels_U0_g_channel_data_V_din;
    sc_signal< sc_logic > extract_channels_U0_g_channel_data_V_write;
    sc_signal< sc_lv<8> > extract_channels_U0_b_channel_data_V_din;
    sc_signal< sc_logic > extract_channels_U0_b_channel_data_V_write;
    sc_signal< sc_logic > extract_channels_U0_ap_start;
    sc_signal< sc_logic > extract_channels_U0_ap_done;
    sc_signal< sc_logic > extract_channels_U0_ap_ready;
    sc_signal< sc_logic > extract_channels_U0_ap_idle;
    sc_signal< sc_logic > extract_channels_U0_ap_continue;
    sc_signal< sc_logic > get_max_from_channel_U0_r_channel_data_V_read;
    sc_signal< sc_logic > get_max_from_channel_U0_g_channel_data_V_read;
    sc_signal< sc_logic > get_max_from_channel_U0_b_channel_data_V_read;
    sc_signal< sc_lv<32> > get_max_from_channel_U0_max_r_out_din;
    sc_signal< sc_logic > get_max_from_channel_U0_max_r_out_write;
    sc_signal< sc_lv<32> > get_max_from_channel_U0_max_g_out_din;
    sc_signal< sc_logic > get_max_from_channel_U0_max_g_out_write;
    sc_signal< sc_lv<32> > get_max_from_channel_U0_max_b_out_din;
    sc_signal< sc_logic > get_max_from_channel_U0_max_b_out_write;
    sc_signal< sc_logic > get_max_from_channel_U0_ap_start;
    sc_signal< sc_logic > get_max_from_channel_U0_ap_done;
    sc_signal< sc_logic > get_max_from_channel_U0_ap_ready;
    sc_signal< sc_logic > get_max_from_channel_U0_ap_idle;
    sc_signal< sc_logic > get_max_from_channel_U0_ap_continue;
    sc_signal< sc_logic > ap_sync_reg_get_max_from_channel_U0_ap_start;
    sc_signal< sc_logic > get_vegetation_image_U0_ap_start;
    sc_signal< sc_logic > get_vegetation_image_U0_ap_done;
    sc_signal< sc_logic > get_vegetation_image_U0_ap_continue;
    sc_signal< sc_logic > get_vegetation_image_U0_ap_idle;
    sc_signal< sc_logic > get_vegetation_image_U0_ap_ready;
    sc_signal< sc_logic > get_vegetation_image_U0_max_r_read;
    sc_signal< sc_logic > get_vegetation_image_U0_max_g_read;
    sc_signal< sc_logic > get_vegetation_image_U0_max_b_read;
    sc_signal< sc_lv<32> > get_vegetation_image_U0_max_r_out_din;
    sc_signal< sc_logic > get_vegetation_image_U0_max_r_out_write;
    sc_signal< sc_lv<32> > get_vegetation_image_U0_max_g_out_din;
    sc_signal< sc_logic > get_vegetation_image_U0_max_g_out_write;
    sc_signal< sc_lv<32> > get_vegetation_image_U0_max_b_out_din;
    sc_signal< sc_logic > get_vegetation_image_U0_max_b_out_write;
    sc_signal< sc_logic > ap_sync_reg_get_vegetation_image_U0_ap_start;
    sc_signal< sc_logic > get_exg_image_U0_ap_start;
    sc_signal< sc_logic > get_exg_image_U0_ap_done;
    sc_signal< sc_logic > get_exg_image_U0_ap_continue;
    sc_signal< sc_logic > get_exg_image_U0_ap_idle;
    sc_signal< sc_logic > get_exg_image_U0_ap_ready;
    sc_signal< sc_logic > get_exg_image_U0_r_channel_data_V_read;
    sc_signal< sc_logic > get_exg_image_U0_g_channel_data_V_read;
    sc_signal< sc_logic > get_exg_image_U0_b_channel_data_V_read;
    sc_signal< sc_logic > get_exg_image_U0_max_r_read;
    sc_signal< sc_logic > get_exg_image_U0_max_g_read;
    sc_signal< sc_logic > get_exg_image_U0_max_b_read;
    sc_signal< sc_lv<32> > get_exg_image_U0_veg_img_data_V_din;
    sc_signal< sc_logic > get_exg_image_U0_veg_img_data_V_write;
    sc_signal< sc_lv<28> > get_exg_image_U0_min_value_V_out_din;
    sc_signal< sc_logic > get_exg_image_U0_min_value_V_out_write;
    sc_signal< sc_lv<29> > get_exg_image_U0_max_value_V_out_din;
    sc_signal< sc_logic > get_exg_image_U0_max_value_V_out_write;
    sc_signal< sc_logic > ap_sync_reg_get_exg_image_U0_ap_start;
    sc_signal< sc_logic > get_vegetation_image_3_U0_ap_start;
    sc_signal< sc_logic > get_vegetation_image_3_U0_ap_done;
    sc_signal< sc_logic > get_vegetation_image_3_U0_ap_continue;
    sc_signal< sc_logic > get_vegetation_image_3_U0_ap_idle;
    sc_signal< sc_logic > get_vegetation_image_3_U0_ap_ready;
    sc_signal< sc_logic > get_vegetation_image_3_U0_max_value_V_read;
    sc_signal< sc_lv<24> > get_vegetation_image_3_U0_ap_return;
    sc_signal< sc_logic > ap_sync_reg_get_vegetation_image_3_U0_ap_start;
    sc_signal< sc_logic > ap_channel_done_extLd_cast_loc_chann;
    sc_signal< sc_logic > extLd_cast_loc_chann_full_n;
    sc_signal< sc_logic > get_vegetation_image_2_U0_ap_start;
    sc_signal< sc_logic > get_vegetation_image_2_U0_ap_done;
    sc_signal< sc_logic > get_vegetation_image_2_U0_ap_continue;
    sc_signal< sc_logic > get_vegetation_image_2_U0_ap_idle;
    sc_signal< sc_logic > get_vegetation_image_2_U0_ap_ready;
    sc_signal< sc_logic > get_vegetation_image_2_U0_min_value_V_read;
    sc_signal< sc_lv<28> > get_vegetation_image_2_U0_min_value_V_out_din;
    sc_signal< sc_logic > get_vegetation_image_2_U0_min_value_V_out_write;
    sc_signal< sc_lv<24> > get_vegetation_image_2_U0_ap_return;
    sc_signal< sc_logic > ap_channel_done_sub_ln703_cast_loc_c;
    sc_signal< sc_logic > sub_ln703_cast_loc_c_full_n;
    sc_signal< sc_logic > convert_fp_to_8b770_U0_ap_start;
    sc_signal< sc_logic > convert_fp_to_8b770_U0_ap_done;
    sc_signal< sc_logic > convert_fp_to_8b770_U0_ap_continue;
    sc_signal< sc_logic > convert_fp_to_8b770_U0_ap_idle;
    sc_signal< sc_logic > convert_fp_to_8b770_U0_ap_ready;
    sc_signal< sc_logic > convert_fp_to_8b770_U0_min_value_V_c17_read;
    sc_signal< sc_logic > convert_fp_to_8b770_U0_veg_temp_data_V_read;
    sc_signal< sc_lv<8> > convert_fp_to_8b770_U0_img_out_data_V_din;
    sc_signal< sc_logic > convert_fp_to_8b770_U0_img_out_data_V_write;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_lv<9> > img_in_0_rows_channe_dout;
    sc_signal< sc_logic > img_in_0_rows_channe_empty_n;
    sc_signal< sc_lv<10> > img_in_0_cols_channe_dout;
    sc_signal< sc_logic > img_in_0_cols_channe_empty_n;
    sc_signal< sc_logic > img_in_cols_c_i_full_n;
    sc_signal< sc_lv<10> > img_in_cols_c_i_dout;
    sc_signal< sc_logic > img_in_cols_c_i_empty_n;
    sc_signal< sc_logic > img_in_0_data_V_full_n;
    sc_signal< sc_lv<24> > img_in_0_data_V_dout;
    sc_signal< sc_logic > img_in_0_data_V_empty_n;
    sc_signal< sc_logic > img_in_1_data_V_full_n;
    sc_signal< sc_lv<24> > img_in_1_data_V_dout;
    sc_signal< sc_logic > img_in_1_data_V_empty_n;
    sc_signal< sc_logic > img_in_2_data_V_full_n;
    sc_signal< sc_lv<24> > img_in_2_data_V_dout;
    sc_signal< sc_logic > img_in_2_data_V_empty_n;
    sc_signal< sc_logic > img_in_3_data_V_full_n;
    sc_signal< sc_lv<24> > img_in_3_data_V_dout;
    sc_signal< sc_logic > img_in_3_data_V_empty_n;
    sc_signal< sc_logic > r_channel_data_V_full_n;
    sc_signal< sc_lv<8> > r_channel_data_V_dout;
    sc_signal< sc_logic > r_channel_data_V_empty_n;
    sc_signal< sc_logic > extract_channels_U0_r_channel_data_V_empty_n;
    sc_signal< sc_logic > extract_channels_U0_r_channel_data_V_read;
    sc_signal< sc_lv<8> > extract_channels_U0_r_channel_data_V_dout;
    sc_signal< sc_logic > g_channel_data_V_full_n;
    sc_signal< sc_lv<8> > g_channel_data_V_dout;
    sc_signal< sc_logic > g_channel_data_V_empty_n;
    sc_signal< sc_logic > extract_channels_U0_g_channel_data_V_empty_n;
    sc_signal< sc_logic > extract_channels_U0_g_channel_data_V_read;
    sc_signal< sc_lv<8> > extract_channels_U0_g_channel_data_V_dout;
    sc_signal< sc_logic > b_channel_data_V_full_n;
    sc_signal< sc_lv<8> > b_channel_data_V_dout;
    sc_signal< sc_logic > b_channel_data_V_empty_n;
    sc_signal< sc_logic > extract_channels_U0_b_channel_data_V_empty_n;
    sc_signal< sc_logic > extract_channels_U0_b_channel_data_V_read;
    sc_signal< sc_lv<8> > extract_channels_U0_b_channel_data_V_dout;
    sc_signal< sc_logic > max_r_c_i_full_n;
    sc_signal< sc_lv<32> > max_r_c_i_dout;
    sc_signal< sc_logic > max_r_c_i_empty_n;
    sc_signal< sc_logic > max_g_c_i_full_n;
    sc_signal< sc_lv<32> > max_g_c_i_dout;
    sc_signal< sc_logic > max_g_c_i_empty_n;
    sc_signal< sc_logic > max_b_c_i_full_n;
    sc_signal< sc_lv<32> > max_b_c_i_dout;
    sc_signal< sc_logic > max_b_c_i_empty_n;
    sc_signal< sc_logic > max_r_c14_i_full_n;
    sc_signal< sc_lv<32> > max_r_c14_i_dout;
    sc_signal< sc_logic > max_r_c14_i_empty_n;
    sc_signal< sc_logic > max_g_c15_i_full_n;
    sc_signal< sc_lv<32> > max_g_c15_i_dout;
    sc_signal< sc_logic > max_g_c15_i_empty_n;
    sc_signal< sc_logic > max_b_c16_i_full_n;
    sc_signal< sc_lv<32> > max_b_c16_i_dout;
    sc_signal< sc_logic > max_b_c16_i_empty_n;
    sc_signal< sc_logic > veg_temp_data_V_full_n;
    sc_signal< sc_lv<32> > veg_temp_data_V_dout;
    sc_signal< sc_logic > veg_temp_data_V_empty_n;
    sc_signal< sc_logic > min_value_V_c_i_full_n;
    sc_signal< sc_lv<28> > min_value_V_c_i_dout;
    sc_signal< sc_logic > min_value_V_c_i_empty_n;
    sc_signal< sc_logic > max_value_V_c_i_full_n;
    sc_signal< sc_lv<29> > max_value_V_c_i_dout;
    sc_signal< sc_logic > max_value_V_c_i_empty_n;
    sc_signal< sc_lv<24> > extLd_cast_loc_chann_dout;
    sc_signal< sc_logic > extLd_cast_loc_chann_empty_n;
    sc_signal< sc_logic > min_value_V_c17_i_full_n;
    sc_signal< sc_lv<28> > min_value_V_c17_i_dout;
    sc_signal< sc_logic > min_value_V_c17_i_empty_n;
    sc_signal< sc_lv<24> > sub_ln703_cast_loc_c_dout;
    sc_signal< sc_logic > sub_ln703_cast_loc_c_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > ap_sync_reg_get_vegetation_image_113_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_get_vegetation_image_113_U0_ap_ready;
    sc_signal< sc_lv<2> > get_vegetation_image_113_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_duplicateMat635769_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_duplicateMat635769_U0_ap_ready;
    sc_signal< sc_lv<2> > duplicateMat635769_U0_ap_ready_count;
    sc_signal< sc_logic > get_vegetation_image_113_U0_start_full_n;
    sc_signal< sc_logic > get_vegetation_image_113_U0_start_write;
    sc_signal< sc_lv<1> > start_for_duplicateMat_U0_din;
    sc_signal< sc_logic > start_for_duplicateMat_U0_full_n;
    sc_signal< sc_lv<1> > start_for_duplicateMat_U0_dout;
    sc_signal< sc_logic > start_for_duplicateMat_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_extract_channels_U0_din;
    sc_signal< sc_logic > start_for_extract_channels_U0_full_n;
    sc_signal< sc_lv<1> > start_for_extract_channels_U0_dout;
    sc_signal< sc_logic > start_for_extract_channels_U0_empty_n;
    sc_signal< sc_logic > duplicateMat_U0_start_full_n;
    sc_signal< sc_logic > duplicateMat_U0_start_write;
    sc_signal< sc_logic > extract_channels_U0_start_full_n;
    sc_signal< sc_logic > extract_channels_U0_start_write;
    sc_signal< sc_logic > get_max_from_channel_U0_start_full_n;
    sc_signal< sc_logic > get_max_from_channel_U0_start_write;
    sc_signal< sc_logic > get_vegetation_image_U0_start_full_n;
    sc_signal< sc_logic > get_vegetation_image_U0_start_write;
    sc_signal< sc_logic > get_exg_image_U0_start_full_n;
    sc_signal< sc_logic > get_exg_image_U0_start_write;
    sc_signal< sc_logic > get_vegetation_image_3_U0_start_full_n;
    sc_signal< sc_logic > get_vegetation_image_3_U0_start_write;
    sc_signal< sc_logic > get_vegetation_image_2_U0_start_full_n;
    sc_signal< sc_logic > get_vegetation_image_2_U0_start_write;
    sc_signal< sc_logic > convert_fp_to_8b770_U0_start_full_n;
    sc_signal< sc_logic > convert_fp_to_8b770_U0_start_write;
    static const sc_logic ap_const_logic_0;
    static const bool ap_const_boolean_1;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<8> ap_const_lv8_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const2();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_ap_channel_done_extLd_cast_loc_chann();
    void thread_ap_channel_done_img_in_0_cols_channe();
    void thread_ap_channel_done_img_in_0_rows_channe();
    void thread_ap_channel_done_sub_ln703_cast_loc_c();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_channel_write_img_in_0_cols_channe();
    void thread_ap_sync_channel_write_img_in_0_rows_channe();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_duplicateMat635769_U0_ap_ready();
    void thread_ap_sync_get_vegetation_image_113_U0_ap_ready();
    void thread_ap_sync_ready();
    void thread_convert_fp_to_8b770_U0_ap_continue();
    void thread_convert_fp_to_8b770_U0_ap_start();
    void thread_convert_fp_to_8b770_U0_start_full_n();
    void thread_convert_fp_to_8b770_U0_start_write();
    void thread_duplicateMat635769_U0_ap_continue();
    void thread_duplicateMat635769_U0_ap_start();
    void thread_duplicateMat635769_U0_start_full_n();
    void thread_duplicateMat_U0_ap_continue();
    void thread_duplicateMat_U0_ap_start();
    void thread_duplicateMat_U0_start_full_n();
    void thread_duplicateMat_U0_start_write();
    void thread_extract_channels_U0_ap_continue();
    void thread_extract_channels_U0_ap_start();
    void thread_extract_channels_U0_b_channel_data_V_dout();
    void thread_extract_channels_U0_b_channel_data_V_empty_n();
    void thread_extract_channels_U0_b_channel_data_V_read();
    void thread_extract_channels_U0_g_channel_data_V_dout();
    void thread_extract_channels_U0_g_channel_data_V_empty_n();
    void thread_extract_channels_U0_g_channel_data_V_read();
    void thread_extract_channels_U0_r_channel_data_V_dout();
    void thread_extract_channels_U0_r_channel_data_V_empty_n();
    void thread_extract_channels_U0_r_channel_data_V_read();
    void thread_extract_channels_U0_start_full_n();
    void thread_extract_channels_U0_start_write();
    void thread_get_exg_image_U0_ap_continue();
    void thread_get_exg_image_U0_ap_start();
    void thread_get_exg_image_U0_start_full_n();
    void thread_get_exg_image_U0_start_write();
    void thread_get_max_from_channel_U0_ap_continue();
    void thread_get_max_from_channel_U0_ap_start();
    void thread_get_max_from_channel_U0_start_full_n();
    void thread_get_max_from_channel_U0_start_write();
    void thread_get_vegetation_image_113_U0_ap_continue();
    void thread_get_vegetation_image_113_U0_ap_start();
    void thread_get_vegetation_image_113_U0_start_full_n();
    void thread_get_vegetation_image_113_U0_start_write();
    void thread_get_vegetation_image_2_U0_ap_continue();
    void thread_get_vegetation_image_2_U0_ap_start();
    void thread_get_vegetation_image_2_U0_start_full_n();
    void thread_get_vegetation_image_2_U0_start_write();
    void thread_get_vegetation_image_3_U0_ap_continue();
    void thread_get_vegetation_image_3_U0_ap_start();
    void thread_get_vegetation_image_3_U0_start_full_n();
    void thread_get_vegetation_image_3_U0_start_write();
    void thread_get_vegetation_image_U0_ap_continue();
    void thread_get_vegetation_image_U0_ap_start();
    void thread_get_vegetation_image_U0_start_full_n();
    void thread_get_vegetation_image_U0_start_write();
    void thread_img_in_cols_read();
    void thread_img_in_data_V_read();
    void thread_img_out_data_V_din();
    void thread_img_out_data_V_write();
    void thread_internal_ap_ready();
    void thread_real_start();
    void thread_start_for_duplicateMat_U0_din();
    void thread_start_for_extract_channels_U0_din();
    void thread_start_out();
    void thread_start_write();
};

}

using namespace ap_rtl;

#endif
