// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _xfChannelCombine_HH_
#define _xfChannelCombine_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct xfChannelCombine : public sc_module {
    // Port declarations 25
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_in< sc_logic > start_full_n;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > start_out;
    sc_out< sc_logic > start_write;
    sc_in< sc_lv<8> > p_in1_V_V_dout;
    sc_in< sc_logic > p_in1_V_V_empty_n;
    sc_out< sc_logic > p_in1_V_V_read;
    sc_in< sc_lv<8> > p_in2_V_V_dout;
    sc_in< sc_logic > p_in2_V_V_empty_n;
    sc_out< sc_logic > p_in2_V_V_read;
    sc_in< sc_lv<8> > p_in3_V_V_dout;
    sc_in< sc_logic > p_in3_V_V_empty_n;
    sc_out< sc_logic > p_in3_V_V_read;
    sc_out< sc_lv<24> > p_out_V_V_din;
    sc_in< sc_logic > p_out_V_V_full_n;
    sc_out< sc_logic > p_out_V_V_write;
    sc_in< sc_lv<10> > p_src1_cols_load7_loc_dout;
    sc_in< sc_logic > p_src1_cols_load7_loc_empty_n;
    sc_out< sc_logic > p_src1_cols_load7_loc_read;


    // Module declarations
    xfChannelCombine(sc_module_name name);
    SC_HAS_PROCESS(xfChannelCombine);

    ~xfChannelCombine();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > real_start;
    sc_signal< sc_logic > start_once_reg;
    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<3> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > internal_ap_ready;
    sc_signal< sc_logic > p_in1_V_V_blk_n;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > icmp_ln118_fu_127_p2;
    sc_signal< sc_logic > p_in2_V_V_blk_n;
    sc_signal< sc_logic > p_in3_V_V_blk_n;
    sc_signal< sc_logic > p_out_V_V_blk_n;
    sc_signal< sc_logic > p_src1_cols_load7_loc_blk_n;
    sc_signal< sc_lv<16> > sext_ln330_fu_111_p1;
    sc_signal< sc_lv<16> > sext_ln330_reg_149;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<8> > i_fu_121_p2;
    sc_signal< sc_lv<8> > i_reg_157;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<16> > j_fu_132_p2;
    sc_signal< bool > ap_block_state3;
    sc_signal< sc_lv<8> > i_0_i_i_i_reg_89;
    sc_signal< sc_lv<16> > j_0_i_i_i_reg_100;
    sc_signal< sc_lv<1> > icmp_ln113_fu_115_p2;
    sc_signal< sc_lv<3> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<3> ap_ST_fsm_state1;
    static const sc_lv<3> ap_ST_fsm_state2;
    static const sc_lv<3> ap_ST_fsm_state3;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<8> ap_const_lv8_B4;
    static const sc_lv<8> ap_const_lv8_1;
    static const sc_lv<16> ap_const_lv16_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_block_state1();
    void thread_ap_block_state3();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_i_fu_121_p2();
    void thread_icmp_ln113_fu_115_p2();
    void thread_icmp_ln118_fu_127_p2();
    void thread_internal_ap_ready();
    void thread_j_fu_132_p2();
    void thread_p_in1_V_V_blk_n();
    void thread_p_in1_V_V_read();
    void thread_p_in2_V_V_blk_n();
    void thread_p_in2_V_V_read();
    void thread_p_in3_V_V_blk_n();
    void thread_p_in3_V_V_read();
    void thread_p_out_V_V_blk_n();
    void thread_p_out_V_V_din();
    void thread_p_out_V_V_write();
    void thread_p_src1_cols_load7_loc_blk_n();
    void thread_p_src1_cols_load7_loc_read();
    void thread_real_start();
    void thread_sext_ln330_fu_111_p1();
    void thread_start_out();
    void thread_start_write();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
