-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2.1
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity duplicateMat438_Loop_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    dst_V_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    dst_V_V_empty_n : IN STD_LOGIC;
    dst_V_V_read : OUT STD_LOGIC;
    p_dst1_data_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst1_data_V_full_n : IN STD_LOGIC;
    p_dst1_data_V_write : OUT STD_LOGIC;
    dst1_V_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    dst1_V_V_empty_n : IN STD_LOGIC;
    dst1_V_V_read : OUT STD_LOGIC;
    p_dst2_data_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    p_dst2_data_V_full_n : IN STD_LOGIC;
    p_dst2_data_V_write : OUT STD_LOGIC );
end;


architecture behav of duplicateMat438_Loop_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv8_B4 : STD_LOGIC_VECTOR (7 downto 0) := "10110100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv9_140 : STD_LOGIC_VECTOR (8 downto 0) := "101000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal dst_V_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln109_reg_139 : STD_LOGIC_VECTOR (0 downto 0);
    signal call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n : STD_LOGIC;
    signal p_dst1_data_V_blk_n : STD_LOGIC;
    signal dst1_V_V_blk_n : STD_LOGIC;
    signal call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n : STD_LOGIC;
    signal p_dst2_data_V_blk_n : STD_LOGIC;
    signal j2_0_reg_79 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln106_fu_106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_fu_112_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_reg_134 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln109_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal j_fu_124_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state3 : STD_LOGIC;
    signal call_ln114_write797_fu_90_ap_start : STD_LOGIC;
    signal call_ln114_write797_fu_90_ap_done : STD_LOGIC;
    signal call_ln114_write797_fu_90_ap_idle : STD_LOGIC;
    signal call_ln114_write797_fu_90_ap_ready : STD_LOGIC;
    signal call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_din : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_write : STD_LOGIC;
    signal call_ln114_write797_fu_90_ap_ce : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter0_ignore_call3 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1_ignore_call3 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp27 : BOOLEAN;
    signal call_ln115_write797_fu_98_ap_start : STD_LOGIC;
    signal call_ln115_write797_fu_98_ap_done : STD_LOGIC;
    signal call_ln115_write797_fu_98_ap_idle : STD_LOGIC;
    signal call_ln115_write797_fu_98_ap_ready : STD_LOGIC;
    signal call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_din : STD_LOGIC_VECTOR (7 downto 0);
    signal call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_write : STD_LOGIC;
    signal call_ln115_write797_fu_98_ap_ce : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter0_ignore_call5 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1_ignore_call5 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_ignoreCallOp29 : BOOLEAN;
    signal i1_0_reg_68 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal call_ln114_write797_fu_90_ap_start_reg : STD_LOGIC := '0';
    signal call_ln115_write797_fu_98_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component write797 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        val_V : IN STD_LOGIC_VECTOR (7 downto 0);
        Mat_0_180_320_1_data_V_addr_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        Mat_0_180_320_1_data_V_addr_full_n : IN STD_LOGIC;
        Mat_0_180_320_1_data_V_addr_write : OUT STD_LOGIC;
        Mat_0_180_320_1_data_V_addr_blk_n : OUT STD_LOGIC;
        ap_ce : IN STD_LOGIC );
    end component;



begin
    call_ln114_write797_fu_90 : component write797
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ln114_write797_fu_90_ap_start,
        ap_done => call_ln114_write797_fu_90_ap_done,
        ap_idle => call_ln114_write797_fu_90_ap_idle,
        ap_ready => call_ln114_write797_fu_90_ap_ready,
        val_V => dst_V_V_dout,
        Mat_0_180_320_1_data_V_addr_din => call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_din,
        Mat_0_180_320_1_data_V_addr_full_n => p_dst1_data_V_full_n,
        Mat_0_180_320_1_data_V_addr_write => call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_write,
        Mat_0_180_320_1_data_V_addr_blk_n => call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n,
        ap_ce => call_ln114_write797_fu_90_ap_ce);

    call_ln115_write797_fu_98 : component write797
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => call_ln115_write797_fu_98_ap_start,
        ap_done => call_ln115_write797_fu_98_ap_done,
        ap_idle => call_ln115_write797_fu_98_ap_idle,
        ap_ready => call_ln115_write797_fu_98_ap_ready,
        val_V => dst1_V_V_dout,
        Mat_0_180_320_1_data_V_addr_din => call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_din,
        Mat_0_180_320_1_data_V_addr_full_n => p_dst2_data_V_full_n,
        Mat_0_180_320_1_data_V_addr_write => call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_write,
        Mat_0_180_320_1_data_V_addr_blk_n => call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n,
        ap_ce => call_ln115_write797_fu_98_ap_ce);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((icmp_ln106_fu_106_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln106_fu_106_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state3) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state3);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((icmp_ln106_fu_106_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    call_ln114_write797_fu_90_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                call_ln114_write797_fu_90_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln109_fu_118_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    call_ln114_write797_fu_90_ap_start_reg <= ap_const_logic_1;
                elsif ((call_ln114_write797_fu_90_ap_ready = ap_const_logic_1)) then 
                    call_ln114_write797_fu_90_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    call_ln115_write797_fu_98_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                call_ln115_write797_fu_98_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln109_fu_118_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    call_ln115_write797_fu_98_ap_start_reg <= ap_const_logic_1;
                elsif ((call_ln115_write797_fu_98_ap_ready = ap_const_logic_1)) then 
                    call_ln115_write797_fu_98_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i1_0_reg_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                i1_0_reg_68 <= i_reg_134;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i1_0_reg_68 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    j2_0_reg_79_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln109_fu_118_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                j2_0_reg_79 <= j_fu_124_p2;
            elsif (((icmp_ln106_fu_106_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j2_0_reg_79 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_134 <= i_fu_112_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln109_reg_139 <= icmp_ln109_fu_118_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln106_fu_106_p2, ap_CS_fsm_state2, icmp_ln109_fu_118_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln106_fu_106_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((icmp_ln109_fu_118_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((icmp_ln109_fu_118_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(2);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(dst_V_V_empty_n, dst1_V_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln109_reg_139, call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n, call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln109_reg_139 = ap_const_lv1_1) and (call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst1_V_V_empty_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst_V_V_empty_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp27_assign_proc : process(dst_V_V_empty_n, dst1_V_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln109_reg_139, call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp27 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln109_reg_139 = ap_const_lv1_1) and (call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst1_V_V_empty_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst_V_V_empty_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_11001_ignoreCallOp29_assign_proc : process(dst_V_V_empty_n, dst1_V_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln109_reg_139, call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n)
    begin
                ap_block_pp0_stage0_11001_ignoreCallOp29 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst1_V_V_empty_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst_V_V_empty_n = ap_const_logic_0))));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(dst_V_V_empty_n, dst1_V_V_empty_n, ap_enable_reg_pp0_iter1, icmp_ln109_reg_139, call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n, call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (((icmp_ln109_reg_139 = ap_const_lv1_1) and (call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst1_V_V_empty_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst_V_V_empty_n = ap_const_logic_0))));
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state3_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter0_ignore_call3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter0_ignore_call5 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state4_pp0_stage0_iter1_assign_proc : process(dst_V_V_empty_n, dst1_V_V_empty_n, icmp_ln109_reg_139, call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n, call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n)
    begin
                ap_block_state4_pp0_stage0_iter1 <= (((icmp_ln109_reg_139 = ap_const_lv1_1) and (call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst1_V_V_empty_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst_V_V_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state4_pp0_stage0_iter1_ignore_call3_assign_proc : process(dst_V_V_empty_n, dst1_V_V_empty_n, icmp_ln109_reg_139, call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n)
    begin
                ap_block_state4_pp0_stage0_iter1_ignore_call3 <= (((icmp_ln109_reg_139 = ap_const_lv1_1) and (call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst1_V_V_empty_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst_V_V_empty_n = ap_const_logic_0)));
    end process;


    ap_block_state4_pp0_stage0_iter1_ignore_call5_assign_proc : process(dst_V_V_empty_n, dst1_V_V_empty_n, icmp_ln109_reg_139, call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n)
    begin
                ap_block_state4_pp0_stage0_iter1_ignore_call5 <= (((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst1_V_V_empty_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n = ap_const_logic_0)) or ((icmp_ln109_reg_139 = ap_const_lv1_1) and (dst_V_V_empty_n = ap_const_logic_0)));
    end process;


    ap_condition_pp0_exit_iter0_state3_assign_proc : process(icmp_ln109_fu_118_p2)
    begin
        if ((icmp_ln109_fu_118_p2 = ap_const_lv1_0)) then 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state3 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, icmp_ln106_fu_106_p2, ap_CS_fsm_state2)
    begin
        if (((icmp_ln106_fu_106_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(icmp_ln106_fu_106_p2, ap_CS_fsm_state2)
    begin
        if (((icmp_ln106_fu_106_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    call_ln114_write797_fu_90_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_ignoreCallOp27)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp27))) then 
            call_ln114_write797_fu_90_ap_ce <= ap_const_logic_1;
        else 
            call_ln114_write797_fu_90_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    call_ln114_write797_fu_90_ap_start <= call_ln114_write797_fu_90_ap_start_reg;

    call_ln115_write797_fu_98_ap_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001_ignoreCallOp29)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_ignoreCallOp29))) then 
            call_ln115_write797_fu_98_ap_ce <= ap_const_logic_1;
        else 
            call_ln115_write797_fu_98_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

    call_ln115_write797_fu_98_ap_start <= call_ln115_write797_fu_98_ap_start_reg;

    dst1_V_V_blk_n_assign_proc : process(dst1_V_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln109_reg_139)
    begin
        if (((icmp_ln109_reg_139 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst1_V_V_blk_n <= dst1_V_V_empty_n;
        else 
            dst1_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dst1_V_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln109_reg_139, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln109_reg_139 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst1_V_V_read <= ap_const_logic_1;
        else 
            dst1_V_V_read <= ap_const_logic_0;
        end if; 
    end process;


    dst_V_V_blk_n_assign_proc : process(dst_V_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln109_reg_139)
    begin
        if (((icmp_ln109_reg_139 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_V_V_blk_n <= dst_V_V_empty_n;
        else 
            dst_V_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    dst_V_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln109_reg_139, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln109_reg_139 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            dst_V_V_read <= ap_const_logic_1;
        else 
            dst_V_V_read <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_112_p2 <= std_logic_vector(unsigned(i1_0_reg_68) + unsigned(ap_const_lv8_1));
    icmp_ln106_fu_106_p2 <= "1" when (unsigned(i1_0_reg_68) < unsigned(ap_const_lv8_B4)) else "0";
    icmp_ln109_fu_118_p2 <= "1" when (unsigned(j2_0_reg_79) < unsigned(ap_const_lv9_140)) else "0";
    j_fu_124_p2 <= std_logic_vector(unsigned(j2_0_reg_79) + unsigned(ap_const_lv9_1));

    p_dst1_data_V_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln109_reg_139, call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n)
    begin
        if (((icmp_ln109_reg_139 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_dst1_data_V_blk_n <= call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_blk_n;
        else 
            p_dst1_data_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst1_data_V_din <= call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_din;

    p_dst1_data_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln109_reg_139, call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_write)
    begin
        if (((icmp_ln109_reg_139 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_dst1_data_V_write <= call_ln114_write797_fu_90_Mat_0_180_320_1_data_V_addr_write;
        else 
            p_dst1_data_V_write <= ap_const_logic_0;
        end if; 
    end process;


    p_dst2_data_V_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln109_reg_139, call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n)
    begin
        if (((icmp_ln109_reg_139 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_dst2_data_V_blk_n <= call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_blk_n;
        else 
            p_dst2_data_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    p_dst2_data_V_din <= call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_din;

    p_dst2_data_V_write_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln109_reg_139, call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_write)
    begin
        if (((icmp_ln109_reg_139 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            p_dst2_data_V_write <= call_ln115_write797_fu_98_Mat_0_180_320_1_data_V_addr_write;
        else 
            p_dst2_data_V_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
